# install.packages(tidyverse)
# install.packages(palmerpenguins)
# install.packages(nycflights13)
# install.packages(gapminder)
# install.packages(janitor)
# install.packages(styler)
# install.packages(babynames)
# install.packages(usethis)
# install.packages(reprex)
# install.packages(ggridges)
# install.packages(hexbin)
# install.packages(ggrepel)
library(tidyverse)
library(palmerpenguins)
library(nycflights13)
library(gapminder)
library(janitor)
library(styler)
library(babynames)
library(usethis)
library(reprex)
library(ggridges)
library(hexbin)
library(ggrepel)
#deck <- read.csv("R4DS/deck.csv")
rscripts <- Sys.glob("R4DS/*.R")
sapply(rscripts, source)
