library(tidyverse)
library(palmerpenguins)
library(nycflights13)
library(gapminder)
library(janitor)
library(styler)
library(babynames)
library(usethis)
library(reprex)
library(ggridges)
#library(ggrepel)
#deck <- read.csv("R4DS/deck.csv")
rscripts <- Sys.glob("R4DS/*.R")
sapply(rscripts, source)
